//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SpriteEdit.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDS_MAIN_TOOLBAR                101
#define IDS_WINDOWS_MANAGER             107
#define IDR_MAINFRAME                   128
#define IDR_SPRITETYPE                  129
#define IDR_CONTEXT_MENU                130
#define IDR_POPUP_TOOLBAR               131
#define IDB_WORKSPACE                   147
#define IDD_SPRITE_PAGE                 158
#define IDD_EMPTY_PAGE                  159
#define IDD_FRAME_PAGE                  160
#define IDD_OPTIONS                     161
#define IDB_COPY_ALL                    162
#define IDB_MOVE_DOWN                   163
#define IDB_MOVE_UP                     164
#define IDB_SUB_DOWN                    165
#define IDB_SUB_UP                      166
#define IDB_NEW_FRAME                   167
#define IDB_NEW_SUBFRAME                168
#define IDB_FIRST_FRAME                 169
#define IDB_LAST_FRAME                  170
#define IDB_PREV_FRAME                  171
#define IDB_NEXT_FRAME                  172
#define IDB_PLAY                        173
#define IDB_STOP                        174
#define IDD_SPRITE_PROP_PAGE            175
#define IDD_PROJECT_ROOT                176
#define IDD_BACKGROUND                  178
#define IDD_DIALOG1                     179
#define IDD_SCRIPTS                     179
#define IDB_PROPERTIES                  181
#define IDC_COMPANY_URL                 1041
#define IDC_BUTTON1                     1042
#define IDC_FRAME_UP                    1042
#define IDC_NO_IMAGE                    1042
#define IDC_COMPANY_WEB                 1042
#define IDC_SPRITE                      1043
#define IDC_EMPTY_NOTE                  1044
#define IDC_FRAME_DOWN                  1044
#define IDC_ACCELERATION                1045
#define IDC_SUBFRAME_UP                 1045
#define IDC_CUSTOM_PATHS                1046
#define IDC_SUBFRAME_DOWN               1046
#define IDC_EDIT_INI                    1047
#define IDC_ADD_FRAME                   1047
#define IDC_REMOVE_FRAME                1048
#define IDC_ADD_SUBFRAME                1049
#define IDC_DELAY                       1050
#define IDC_FIRST_FRAME                 1050
#define IDC_MOVE_X                      1051
#define IDC_PREV_FRAME                  1051
#define IDC_MOVE_Y                      1052
#define IDC_PLAY_STOP                   1052
#define IDC_3D_ONLY                     1053
#define IDC_NEXT_FRAME                  1053
#define IDC_2D_ONLY                     1054
#define IDC_LAST_FRAME                  1054
#define IDC_HOTSPOT_X                   1055
#define IDC_HOTSPOT_Y                   1056
#define IDC_COPY_MOVE                   1057
#define IDC_COPY_HOTSPOT                1058
#define IDC_TRANSPARENT                 1059
#define IDC_ALPHA_COLOR                 1060
#define IDC_ALPHA                       1061
#define IDC_ALPHA_SPIN                  1062
#define IDC_IMAGE                       1063
#define IDC_BROWSE_IMAGE                1064
#define IDC_COPY_DELAY                  1065
#define IDC_TRANS_RGB                   1066
#define IDC_ALPHA_RGB                   1067
#define IDC_LOOPING                     1067
#define IDC_SOUND                       1068
#define IDC_NAME                        1068
#define IDC_BROWSE_SOUND                1069
#define IDC_CONTINUOS                   1069
#define IDC_PRECISE                     1070
#define IDC_COPY_TRANS                  1070
#define IDC_EVENT                       1071
#define IDC_STREAMED                    1071
#define IDC_DECORATION                  1072
#define IDC_STREAMED2                   1072
#define IDC_STREAMED_KEEP_LOADED        1072
#define IDC_KEYFRAME                    1073
#define IDC_KILL_SOUND                  1074
#define IDC_MUTED                       1075
#define IDC_COPY_ALPHA                  1075
#define IDC_FILENAME                    1076
#define IDC_MIRROR_X                    1076
#define IDC_OFFSET_X                    1077
#define IDC_MIRROR_X2                   1077
#define IDC_MIRROR_Y                    1077
#define IDC_OFFSET_Y                    1078
#define IDC_COPY_HOTSPOT2               1078
#define IDC_COPY_MIRROR                 1078
#define IDC_PRODUCT                     1081
#define IDC_TOTAL_TIME                  1082
#define IDC_FORCE_16BIT_TEXTURES        1126
#define IDC_FORCE_TEXTURE_SUBDIVISION   1127
#define IDC_PREVIOUS                    2000
#define IDC_CUSTOM                      2001
#define IDC_CUSTOM_NAME                 2002
#define IDC_PREV_LIST                   2003
#define IDC_BROWSE                      2004
#define IDC_SCRIPT_UP                   2005
#define IDC_SCRIPT_DOWN                 2006
#define IDC_ADD_SCRIPT                  2007
#define IDC_REMOVE_SCRIPT               2008
#define IDC_EDIT                        2009
#define IDC_SCRIPTS                     2010
#define ID_VIEW_CUSTOMIZE               32770
#define ID_VIEW_TOOLBARS                32771
#define ID_VIEW_USER_TOOLBAR1           32793
#define ID_VIEW_USER_TOOLBAR2           32794
#define ID_VIEW_USER_TOOLBAR3           32795
#define ID_VIEW_USER_TOOLBAR4           32796
#define ID_VIEW_USER_TOOLBAR5           32797
#define ID_VIEW_USER_TOOLBAR6           32798
#define ID_VIEW_USER_TOOLBAR7           32799
#define ID_VIEW_USER_TOOLBAR8           32800
#define ID_VIEW_USER_TOOLBAR9           32801
#define ID_VIEW_USER_TOOLBAR10          32802
#define ID_VIEW_WORKSPACE               32803
#define ID_VIEW_OUTPUT                  32804
#define ID_TOOLS_ENTRY                  32805
#define ID_USER_TOOL1                   32806
#define ID_USER_TOOL2                   32807
#define ID_USER_TOOL3                   32808
#define ID_USER_TOOL4                   32809
#define ID_USER_TOOL5                   32810
#define ID_USER_TOOL6                   32811
#define ID_USER_TOOL7                   32812
#define ID_USER_TOOL8                   32813
#define ID_USER_TOOL9                   32814
#define ID_USER_TOOL10                  32815
#define ID_WINDOW_MANAGER               32823
#define ID_VIEW_PROPERTY                32824
#define ID_TOOLS_REFRESH                32825
#define ID_TOOLS_OPTIONS                32826
#define ID_VIEW_BACKGROUND              32827
#define ID_HELP_DOCS                    32828
#define ID_INDICATOR_FPS                59142
#define ID_INDICATOR_MODE               59143
#define ID_INDICATOR_CURSOR             59144

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        182
#define _APS_NEXT_COMMAND_VALUE         32829
#define _APS_NEXT_CONTROL_VALUE         2020
#define _APS_NEXT_SYMED_VALUE           108
#endif
#endif
