//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SceneEdit.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDS_MAIN_TOOLBAR                101
#define IDS_WINDOWS_MANAGER             107
#define IDR_MAINFRAME                   128
#define IDR_SCENETYPE                   129
#define IDR_CONTEXT_MENU                130
#define IDR_POPUP_TOOLBAR               131
#define IDB_WORKSPACE                   147
#define IDD_SCENE_PAGE                  153
#define IDR_LAYER                       154
#define IDB_NODES                       156
#define IDD_OPTIONS                     164
#define IDD_REGION_PAGE                 165
#define IDD_ENTITY_PAGE                 166
#define IDD_EMPTY_PAGE                  167
#define IDC_MOVE_POINT                  167
#define IDD_WAYPOINTS_PAGE              168
#define IDB_MOVE_UP                     168
#define IDB_MOVE_DOWN                   169
#define IDB_PROPERTIES                  170
#define IDB_ADD_ENTITY                  171
#define IDB_ADD_REGION                  172
#define IDB_ADD_POINT                   173
#define IDB_REMOVE_POINT                174
#define IDC_NO_REMOVE                   175
#define IDD_LAYER                       178
#define IDD_SCENE_PROP_PAGE             179
#define IDD_EVENTS                      180
#define IDD_EVENT_PROP                  181
#define IDD_POINT_POS                   183
#define IDR_NEW_ENTITY                  184
#define IDC_ADD_SCALE                   185
#define IDB_ADD_SCALE                   186
#define IDD_SCALE                       187
#define IDR_POPUP_SCALE                 188
#define IDD_SCRIPTS                     190
#define IDD_PROJECT_ROOT                195
#define IDD_SOUND_PAGE                  198
#define IDB_PLAY                        199
#define IDD_CUSTOM_PROP                 200
#define IDD_NEW_PROP                    201
#define IDC_ADD_ROT                     202
#define IDD_ROT                         204
#define IDR_POPUP_ROTATION              205
#define IDB_ADD_ROT                     206
#define IDD_TEMPLATE                    207
#define IDB_OPEN                        208
#define IDD_3D_PAGE                     209
#define IDD_ANIMATION                   210
#define IDC_COMPANY_URL                 1041
#define IDC_COMPANY_WEB                 1042
#define IDC_LAYER_TOOLBAR               1045
#define IDC_NODE_TOOLBAR                1046
#define IDC_LAYERS                      1047
#define IDC_NODES                       1048
#define IDC_ACCELERATION                1049
#define IDC_CUSTOM_PATHS                1056
#define IDC_EDIT_INI                    1057
#define IDC_EMPTY_NOTE                  1058
#define IDC_NAME                        1059
#define IDC_BLOCKED                     1060
#define IDC_CAPTION                     1060
#define IDC_SCALE                       1061
#define IDC_SCALE_SPIN                  1062
#define IDC_ALPHA                       1063
#define IDC_SPRITE                      1065
#define IDC_BROWSE_SPRITE               1066
#define IDC_CURSOR                      1067
#define IDC_BROWSE_CURSOR               1068
#define IDC_FONT                        1069
#define IDC_BROWSE_FONT                 1070
#define IDC_SCALABLE                    1071
#define IDC_REGISTRABLE                 1072
#define IDC_SHADOWABLE                  1073
#define IDC_POS_X                       1074
#define IDC_POS_Y                       1075
#define IDC_EVENTS                      1076
#define IDC_ADD_LAYER                   1077
#define IDC_BROWSE_CAPTION              1077
#define IDC_LAYER_DOWN                  1078
#define IDC_SOUND_PANNING               1078
#define IDC_LAYER_UP                    1079
#define IDC_WIDTH                       1079
#define IDC_VOLUME                      1079
#define IDC_ITEM_NAME                   1079
#define IDC_REMOVE_LAYER                1080
#define IDC_HEIGHT                      1080
#define IDC_START_TIME                  1080
#define IDC_WALK_X                      1080
#define IDC_LAYER_PROPERTIES            1081
#define IDC_IS_MAIN                     1081
#define IDC_WALK_Y                      1081
#define IDC_NODE_UP                     1082
#define IDC_NODE_DOWN                   1083
#define IDC_ADD_REGION                  1084
#define IDC_ADD_ENTITY                  1086
#define IDC_COL_ENTITY                  1086
#define IDC_REMOVE_NODE                 1087
#define IDC_COL_ENTITY_SEL              1087
#define IDC_ADD_POINT                   1088
#define IDC_COL_REGION                  1088
#define IDC_REMOVE_POINT                1089
#define IDC_COL_REGION_SEL              1089
#define IDC_COL_WAYPOINTS               1090
#define IDC_COL_WAYPOINTS_SEL           1091
#define IDC_COL_FRAME                   1092
#define IDC_MARGIN_V                    1093
#define IDC_MARGIN_H                    1094
#define IDC_EVENT_UP                    1094
#define IDC_COL_BLOCKED                 1095
#define IDC_EVENT_DOWN                  1095
#define IDC_COL_BLOCKED_SEL             1096
#define IDC_ADD_EVENT                   1096
#define IDC_REMOVE_EVENT                1097
#define IDC_COL_SCALE                   1097
#define IDC_EVENT_PROPERTIES            1098
#define IDC_COL_DECOR                   1098
#define IDC_COL_DECOR_SEL               1099
#define IDC_EVENT                       1100
#define IDC_BROWSE_SCRIPT               1101
#define IDC_SCRIPT                      1102
#define IDC_SHOW_REGIONS                1105
#define IDC_SHOW_BLOCKED                1106
#define IDC_SHOW_ENTITIES               1107
#define IDC_SHOW_SCALE                  1108
#define IDC_SCRIPTS                     1109
#define IDC_SHOW_DECOR                  1109
#define IDC_SCRIPT_UP                   1110
#define IDC_SCRIPT_DOWN                 1111
#define IDC_ADD_SCRIPT                  1112
#define IDC_REMOVE_SCRIPT               1113
#define IDC_DIVIDE                      1114
#define IDC_EDIT                        1114
#define IDC_SOUND                       1115
#define IDC_BROWSE_SOUND                1116
#define IDC_PLAY                        1117
#define IDC_PROP_LIST                   1117
#define IDC_ADD_PROP                    1118
#define IDC_EDIT_PROP                   1119
#define IDC_REMOVE_PROP                 1120
#define IDC_PROP_NAME                   1121
#define IDC_PROP_VALUE                  1122
#define IDC_VOLUME_SPIN                 1122
#define IDC_TYPE_LAYOUT                 1123
#define IDC_TYPE_DECORATION             1124
#define IDC_TYPE_BLOCKED                1125
#define IDC_FORCE_16BIT_TEXTURES        1126
#define IDC_FORCE_TEXTURE_SUBDIVISION   1127
#define IDC_PRODUCT                     1128
#define IDC_IGNORE_ITEMS                1129
#define IDC_PERSISTENT                  1130
#define IDC_ROTATION                    1131
#define IDC_PERSISTENT2                 1131
#define IDC_CLOSE_UP                    1132
#define IDC_WALK_DIR                    1133
#define IDC_NEW_SCRIPT                  1134
#define IDC_PERSISTENT_SPRITES          1135
#define IDC_WALK_GET                    1140
#define IDC_WALK_SET                    1141
#define IDC_SHOW_GEOMETRY               1141
#define IDC_CAMERA                      1143
#define IDC_GEOMETRY                    1144
#define IDC_BUTTON1                     1145
#define IDC_BROWSE_GEOMETRY             1145
#define IDC_RES_WIDTH                   1146
#define IDC_RES_HEIGHT                  1147
#define IDC_FOV                         1148
#define IDC_OVERRIDE_FOV                1149
#define IDC_FOV_TEXT                    1150
#define IDC_WAYPOINT_HEIGHT             1151
#define IDC_NEAR_PLANE                  1152
#define IDC_EDIT2                       1153
#define IDC_FAR_PLANE                   1153
#define IDC_CHECK1                      1154
#define IDC_2D_PATHFINDING              1154
#define IDC_CAMERA2                     1155
#define IDC_SHADOWS                     1155
#define IDC_LIST1                       1155
#define IDC_ANIM_LIST                   1155
#define IDC_COL_AMBIENT                 1156
#define IDC_SCROLL3D_COMPATIBILITY      1157
#define IDC_FOV_VAL                     1158
#define IDC_EDIT1                       1159
#define IDC_PREVIOUS                    2000
#define IDC_CUSTOM                      2001
#define IDC_CUSTOM_NAME                 2002
#define IDC_PREV_LIST                   2003
#define IDC_BROWSE                      2004
#define IDC_REPOSITORY                  2005
#define IDC_TEMPLATES                   2006
#define IDC_DESC                        2007
#define IDC_PROPS                       2008
#define IDC_DIR                         2010
#define IDC_NAME_LABEL                  2012
#define IDC_DIR_LABEL                   2014
#define ID_VIEW_CUSTOMIZE               32770
#define ID_VIEW_TOOLBARS                32771
#define ID_VIEW_USER_TOOLBAR1           32793
#define ID_VIEW_USER_TOOLBAR2           32794
#define ID_VIEW_USER_TOOLBAR3           32795
#define ID_VIEW_USER_TOOLBAR4           32796
#define ID_VIEW_USER_TOOLBAR5           32797
#define ID_VIEW_USER_TOOLBAR6           32798
#define ID_VIEW_USER_TOOLBAR7           32799
#define ID_VIEW_USER_TOOLBAR8           32800
#define ID_VIEW_USER_TOOLBAR9           32801
#define ID_VIEW_USER_TOOLBAR10          32802
#define ID_VIEW_WORKSPACE               32803
#define ID_VIEW_OUTPUT                  32804
#define ID_TOOLS_ENTRY                  32805
#define ID_USER_TOOL1                   32806
#define ID_USER_TOOL2                   32807
#define ID_USER_TOOL3                   32808
#define ID_USER_TOOL4                   32809
#define ID_USER_TOOL5                   32810
#define ID_USER_TOOL6                   32811
#define ID_USER_TOOL7                   32812
#define ID_USER_TOOL8                   32813
#define ID_USER_TOOL9                   32814
#define ID_USER_TOOL10                  32815
#define ID_VIEW_PROPERTY                32816
#define ID_WINDOW_MANAGER               32823
#define ID_LAYER_UP                     32824
#define ID_LAYER_DOWN                   32825
#define ID_TOOLS_OPTIONS                32827
#define ID_BUTTON32828                  32828
#define ID_SCENE_REFRESH                32829
#define ID_TOOLS_REFRESH                32831
#define ID_NEW_ENTITY_SPRITE            32832
#define ID_NEW_ENTITY_REGION            32833
#define ID_SCALE_PROPERTIES             32834
#define ID_SCALE_REMOVE                 32835
#define ID_ACTOR_LOAD                   32836
#define ID_PLACE_ACTOR                  32837
#define ID_ACTOR_REMOVE                 32838
#define ID_ACTOR_PLACE                  32839
#define ID_ACTOR_COPY_DATA              32841
#define ID_NEW_ENTITY_SOUND             32842
#define ID_ROT_PROPERTIES               32843
#define ID_ROT_REMOVE                   32844
#define ID_HELP_DOCS                    32845
#define ID_ACTOR_CHOOSEANIMATION        32846
#define ID_ACTOR_ANIMATION              32847
#define ID_INDICATOR_FPS                59142
#define ID_INDICATOR_MODE               59143
#define ID_INDICATOR_CURSOR             59144

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        211
#define _APS_NEXT_COMMAND_VALUE         32848
#define _APS_NEXT_CONTROL_VALUE         1160
#define _APS_NEXT_SYMED_VALUE           108
#endif
#endif
