#include "scripts\base.inc"

// here comes the stuff which initializes the scene

actor.SkipTo(400, 400);
actor.Direction = DI_DOWN;
actor.Active = true;


////////////////////////////////////////////////////////////////////////////////
// scene state
global State$$SCENE_NAME$$;


// default values
if(State$$SCENE_NAME$$==null)
{
  State$$SCENE_NAME$$.Visited = false;
  // add scene states here
}



////////////////////////////////////////////////////////////////////////////////
// setup scene according to state variables



////////////////////////////////////////////////////////////////////////////////
if(!State$$SCENE_NAME$$.Visited)
{
  State$$SCENE_NAME$$.Visited = true;

  // this is our first visit in this scene...
}

