
*grp 
*atr Name
*des The internal name of the object.

*atr Caption
*des The caption of the object.

*atr AccCaption
*des A special caption of the object used for accessibility purposes.

*atr X
*des The X position of the object.

*atr Y
*des The Y position of the object.

*atr Height
*ro
*des Returns the current height of the object. In case of actors and entities the scaling is taken into account.

*atr Filename
*ro
*des Returns the filename.

*atr Ready
*ro
*des Returns whether the object isn't currently performing any action.

*atr Interactive
*des Specifies whether the object recieves user input.

*atr SoundPanning
*des Specifies whether the sounds played by this object are automatically panned depending on object's position on screen.

*atr NonIntMouseEvents
*des Specifies if the object can receive the <b>MouseEntry</b> and <b>MouseLeave</b> events even if the game is in non-interactive mode.
