
*atr Active
*des Specifies whether the object is visible on screen

*atr IgnoreItems
*des Specifies whether the object appears to be non-interactive when an inventory item is used on it

*atr SubtitlesPosRelative
*des Specifies whether the <b>SubtitlesPosX</b> and <b>SubtitlesPosY</b> attributes are relative to default position, or absolute screen coordinates

*atr SubtitlesPosX
*des The X position of speech subtitles (either relative to speaker's position or absolute screen coordinates)

*atr SubtitlesPosY
*des The Y position of speech subtitles (either relative to speaker's position or absolute screen coordinates)

*atr SubtitlesWidth
*des Width of speech subtitles. Set to zero to restore the default behavior.

*atr SubtitlesPosXCenter
*des Specifies if the <b>SubtitlesPosX</b> attribute affects the center of the subtitle or its left side.

*atr ParticleEmitter
*ro
*des Returns the reference to the particle emitter object attached to this object, or <b>null</b> if the emitter haven't been initialized yet

*atr NumAttachments
*ro
*des Returns the number of entities attached to this object.


*evn MouseEntry
*des The mouse pointer has been just moved over the object.

*evn MouseLeave
*des The mouse pointer has been just moved away from the object.

