*grp Event functions

*met ApplyEvent(EventName)
*des Applies a named event to the object.
*par EventName A name of the event to be applied to the object.
*ret Returns <b>true</b> it the event has been applied succesfuly.

*met CanHandleEvent(EventName)
*des Queries whether the object has an event handler for a specified event.
*par EventName The name of the event to be checked.
*ret Returns <b>true</b> if the object is able to handle the specified event.


