*evn LeftClick
*des The left mouse button has been pressed.

*evn RightClick
*des The right mouse button has been pressed.

*evn MiddleClick
*des The middle mouse button has been pressed.

*evn LeftDoubleClick
*des The left mouse button has been double-clicked.

*evn RightDoubleClick
*des The right mouse button has been double-clicked.

*evn LeftRelease
*des The left mouse button has been released.

*evn RightRelease
*des The right mouse button has been released.

*evn MiddleRelease
*des The middle mouse button has been released.

*evn MouseWheelUp
*des The mouse wheel has been rolled up.

*evn MouseWheelDown
*des The mouse wheel has been rolled down.

*evn Keypress
*des Some key has been pressed. Use the <b>Keyboard</b> variable to find out the details.
