//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ProjectMan.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_PROJECTYPE                  129
#define IDD_PROPS                       130
#define IDD_TREE                        131
#define IDD_LOG                         132
#define IDR_POPUP_FILE                  137
#define IDR_POPUP_TREE                  145
#define IDD_NEW_FOLDER                  146
#define IDD_PAGE_PACKAGE                147
#define IDR_TOOLBAR_2                   148
#define IDD_COMPILE                     150
#define IDI_ACTOR                       153
#define IDI_WINDOW                      154
#define IDI_DEF                         155
#define IDI_ENTITY                      156
#define IDI_FONT                        157
#define IDI_SCRIPT                      158
#define IDD_VIEWPORT                    159
#define IDD_SAVELOAD                    160
#define IDI_ACTOR3D                     162
#define IDD_PAGE_PLUGINS                166
#define IDD_REMINDER                    167
#define IDC_PROP_LIST                   1000
#define IDC_TREE                        1001
#define IDC_LIST                        1002
#define IDC_FOLDER_NAME                 1003
#define IDC_BUTTON1                     1004
#define IDC_LOAD_BROWSE                 1004
#define IDC_GENERATE                    1004
#define IDC_FILTER_EXCLUDE              1005
#define IDC_SAVE_BROWSE                 1005
#define IDC_SCRIPTS                     1005
#define IDC_MASKS_EXCLUDE               1006
#define IDC_UP                          1006
#define IDC_FILTER_UNCOMPRESS           1007
#define IDC_DOWN                        1007
#define IDC_MASKS_UNCOMPRESS            1008
#define IDC_NEW                         1008
#define IDC_FILTER_SCRIPT               1009
#define IDC_EDIT                        1009
#define IDC_MASKS_SCRIPT                1010
#define IDC_DELETE                      1010
#define IDC_OUTPUT_DIR                  1011
#define IDC_FILTER_COPY                 1011
#define IDC_BROWSE_OUTPUT               1012
#define IDC_MASKS_COPY                  1012
#define IDC_BUILD_MASTER                1013
#define IDC_VERSION                     1014
#define IDC_TITLE_1                     1015
#define IDC_COPY_EXE                    1015
#define IDC_TITLE_2                     1016
#define IDC_EXE_NAME                    1016
#define IDC_PROGRESS                    1017
#define IDC_CHANGE_ICON                 1017
#define IDC_PREVIEW                     1018
#define IDC_ICON_NAME                   1018
#define IDC_MAIL                        1019
#define IDC_BROWSE_ICON                 1019
#define IDC_FULLSCREEN                  1020
#define IDC_WEB                         1020
#define IDC_BIND_PACKAGE                1020
#define IDC_BROWSE_GDF                  1020
#define IDC_POS_X                       1021
#define IDC_COPY_SET                    1021
#define IDC_POS_Y                       1022
#define IDC_SET_NAME                    1022
#define IDC_WIDTH                       1023
#define IDC_PRODUCT                     1023
#define IDC_CHANGE_ICON_SET             1023
#define IDC_HEIGHT                      1024
#define IDC_PACKAGES                    1024
#define IDC_LOAD_FILE                   1025
#define IDC_ICON_NAME_SET               1025
#define IDC_LOAD_X                      1026
#define IDC_BROWSE_ICON_SET             1026
#define IDC_LOAD_Y                      1027
#define IDC_PLUGIN_LIST                 1027
#define IDC_ADD_CRASH_LIB               1027
#define IDC_SAVE_FILE                   1028
#define IDC_EDIT1                       1028
#define IDC_PLUGIN_INFO                 1028
#define IDC_GUID                        1028
#define IDC_ADD_FPS                     1028
#define IDC_SAVE_X                      1029
#define IDC_REMIND_LATER                1029
#define IDC_CHANGE_ICON_SET4            1029
#define IDC_ADD_DEBUG_MODE              1029
#define IDC_SAVE_Y                      1030
#define IDC_ALREADY_DONATED             1030
#define IDC_COPY_D3DX                   1030
#define IDC_DONT_WANNA_DONATE           1031
#define IDC_BROWSE_ICON_SET2            1031
#define IDC_D3DX_HELP                   1031
#define IDC_PAGE                        1032
#define IDD_PROJECT_ROOT                2000
#define IDC_PREVIOUS                    2000
#define IDC_CUSTOM                      2001
#define IDD_TEMPLATE                    2001
#define IDC_CUSTOM_NAME                 2002
#define IDD_PAGE_GENERAL_SETTINGS       2002
#define IDC_PREV_LIST                   2003
#define IDD_GUID                        2003
#define IDC_BROWSE                      2004
#define IDC_REPOSITORY                  2005
#define IDD_COMPAT                      2005
#define IDC_TEMPLATES                   2006
#define IDC_DESC                        2007
#define IDC_PROPS                       2008
#define IDC_NAME                        2009
#define IDC_DIR                         2010
#define IDC_NAME_LABEL                  2012
#define IDC_DIR_LABEL                   2014
#define IDB_NODES                       2015
#define IDB_UP                          2016
#define IDB_DOWN                        2017
#define IDB_PROPS                       2018
#define IDB_DELETE                      2019
#define IDB_NEW                         2020
#define IDD_SCRIPTS                     2021
#define IDC_ACCLERATION                 2022
#define IDC_WME_PATH                    2023
#define IDC_BROWSE_TOOLS                2024
#define IDC_REPOSITORIES                2025
#define IDC_ADD_REPOSITORY              2026
#define IDC_REMOVE_REPOSITORY           2027
#define IDC_CHECK_UPDATES               2028
#define IDC_FORCE_16BIT_TEXTURES        2029
#define IDC_FORCE_TEXTURE_SUBDIVISION   2030
#define IDC_CHECK_UPDATES2              2031
#define IDC_SETTINGS_DLG                2031
#define IDC_GE_DATA                     2031
#define IDC_SETTINGS_DLG2               2032
#define IDC_SHOW_HIDDEN                 2032
#define IDC_GDF_FILE                    2032
#define IDC_THUMBNAIL_FILE              2033
#define IDC_BROWSE_THUMBNAIL            2034
#define IDC_CHECK1                      2035
#define IDC_COMPAT_KILL_METHOD_THREADS  2035
#define IDD_PAGE_FILTERS                30735
#define IDD_PAGE_VISTA                  30736
#define ID_POPUP_FILE_BROWSE            32771
#define ID_POPUP_FILE_REMOVE            32772
#define ID_POPUP_FILE_EDIT              32773
#define ID_POPUP_ADD_ACTOR              32775
#define ID_POPUP_ADD_ENTITY             32776
#define ID_POPUP_ADD_SCENE              32777
#define ID_POPUP_ADD_SCRIPT             32778
#define ID_POPUP_ADD_SPRITE             32779
#define ID_POPUP_ADD_FONT               32780
#define ID_POPUP_ADD_WINDOW             32781
#define ID_POPUP_IMPORT_FILE            32782
#define ID_POPUP_IMPORT_FOLDER          32783
#define ID_POPUP_TREE_EDIT              32785
#define ID_POPUP_TREE_EXPLORE           32786
#define ID_POPUP_TREE_PROMOTE           32787
#define ID_POPUP_TREE_CREATE_FOLDER     32788
#define ID_POPUP_TREE_REFRESH           32789
#define ID_POPUP_TREE_FOLDER_TOP        32790
#define ID_POPUP_TREE_REMOVE            32791
#define ID_POPUP_TREE_DEGRADE           32792
#define ID_POPUP_TREE_PRIMARY_PACKAGE   32793
#define ID_PROJECT_SETTINGS             32794
#define ID_TOOLS_OPTIONS                32795
#define ID_PROJECT_COMPILE              32796
#define ID_PROJECT_RUN                  32798
#define ID_POPUP_TREE_COPY              32799
#define ID_POPUP_TREE_CHECK_SYNTAX      32800
#define ID_HELP_DOCS                    32801
#define ID_HELP_UPDATES                 32802
#define ID_HELP_WEB1                    32804
#define ID_HELP_WEB2                    32805
#define ID_HELP_WEB3                    32806
#define ID_HELP_WEB4                    32807
#define ID_HELP_WEB5                    32808
#define ID_HELP_WEB6                    32809
#define ID_HELP_WEB7                    32810
#define ID_HELP_WEB8                    32811
#define ID_HELP_WEB9                    32812
#define ID_HELP_WEB10                   32813
#define ID_TREE_STARTUP_SCENE           32815
#define ID_POPUP_TREE_STARTUP_SCENE     32816
#define ID_TOOLS_SCENEEDIT              32817
#define ID_TOOLS_SPRITEEDIT             32818
#define ID_POPUP_ADD_ACTOR3D            32825
#define ID_TOOLS_STRINGTABLE            32826
#define ID__                            32828
#define ID_HELP_DONATE                  32829
#define ID_POPUP_TREE_STARTUP_SCENE_D   32830
#define ID__GENERATEGDFFILE             42000
#define ID__GENERATE_GDF                42001
#define ID_GENERATE_GDF                 42002
#define ID_OTHER_OPEN                   42003
#define ID_POPUP_TREE_OPEN              42004
#define ID_OTHER_COMPILETHISPACKAGE     42005
#define ID_POPUP_TREE_COMPILE           42006

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        2006
#define _APS_NEXT_COMMAND_VALUE         42007
#define _APS_NEXT_CONTROL_VALUE         2036
#define _APS_NEXT_SYMED_VALUE           2000
#endif
#endif
