// standard 101 keyboard key codes

var VK_LBUTTON    = 1;
var VK_RBUTTON    = 2;
var VK_CANCEL     = 3;
var VK_MBUTTON    = 4;

var VK_BACK       = 8;
var VK_TAB        = 9;

var VK_CLEAR      = 12;
var VK_RETURN     = 13;

var VK_SHIFT      = 16;
var VK_CONTROL    = 17;
var VK_MENU       = 18;
var VK_PAUSE      = 19;
var VK_CAPITAL    = 20;

var VK_KANA       = 21;
var VK_HANGEUL    = 21;
var VK_HANGUL     = 21;
var VK_JUNJA      = 23;
var VK_FINAL      = 24;
var VK_HANJA      = 25;
var VK_KANJI      = 25;

var VK_ESCAPE     = 27;

var VK_CONVERT    = 28;
var VK_NONCONVERT = 29;
var VK_ACCEPT     = 30;
var VK_MODECHANGE = 31;

var VK_SPACE      = 32;
var VK_PRIOR      = 33;
var VK_NEXT       = 34;
var VK_END        = 35;
var VK_HOME       = 36;
var VK_LEFT       = 37;
var VK_UP         = 38;
var VK_RIGHT      = 39;
var VK_DOWN       = 40;
var VK_SELECT     = 41;
var VK_PRINT      = 42;
var VK_EXECUTE    = 43;
var VK_SNAPSHOT   = 44;
var VK_INSERT     = 45;
var VK_DELETE     = 46;
var VK_HELP       = 47;

var VK_LWIN       = 91;
var VK_RWIN       = 92;
var VK_APPS       = 93;

var VK_NUMPAD0    = 96;
var VK_NUMPAD1    = 97;
var VK_NUMPAD2    = 98;
var VK_NUMPAD3    = 99;
var VK_NUMPAD4    = 100;
var VK_NUMPAD5    = 101;
var VK_NUMPAD6    = 102;
var VK_NUMPAD7    = 103;
var VK_NUMPAD8    = 104;
var VK_NUMPAD9    = 105;
var VK_MULTIPLY   = 106;
var VK_ADD        = 107;
var VK_SEPARATOR  = 108;
var VK_SUBTRACT   = 109;
var VK_DECIMAL    = 110;
var VK_DIVIDE     = 111;
var VK_F1         = 112;
var VK_F2         = 113;
var VK_F3         = 114;
var VK_F4         = 115;
var VK_F5         = 116;
var VK_F6         = 117;
var VK_F7         = 118;
var VK_F8         = 119;
var VK_F9         = 120;
var VK_F10        = 121;
var VK_F11        = 122;
var VK_F12        = 123;
var VK_F13        = 124;
var VK_F14        = 125;
var VK_F15        = 126;
var VK_F16        = 127;
var VK_F17        = 128;
var VK_F18        = 129;
var VK_F19        = 130;
var VK_F20        = 131;
var VK_F21        = 132;
var VK_F22        = 133;
var VK_F23        = 134;
var VK_F24        = 135;

var VK_NUMLOCK    = 144;
var VK_SCROLL     = 145;

var VK_LSHIFT     = 160;
var VK_RSHIFT     = 161;
var VK_LCONTROL   = 162;
var VK_RCONTROL   = 163;
var VK_LMENU      = 164;
var VK_RMENU      = 165;

var VK_PROCESSKEY = 229;

var VK_ATTN       = 246;
var VK_CRSEL      = 247;
var VK_EXSEL      = 248;
var VK_EREOF      = 249;
var VK_PLAY       = 250;
var VK_ZOOM       = 251;
var VK_NONAME     = 252;
var VK_PA1        = 253;
var VK_OEM_CLEAR  = 254;
